<h2>Berichtjes</h2>
<?php if($this->noBerichtjes) { ?>
Er zijn geen ongelezen berichtjes
<?php } else { ?>
<ul data-role="listview" data-inset="true" class="ui-listview ui-listview-inset ui-corner-all ui-shadow">
	<?php foreach ($this->berichtjes as $key => $berichtje) { ?>
		<li class="ui-li ui-li-static ui-body-c ui-corner-top">
			<div class="ui-btn-inner ui-li">
				<div class="ui-btn-text">
					<a href="index.html" class="ui-link-inherit"><?php 
						echo $this->DateFromEpoch()->epoch($berichtje->getDate());
						echo ' '; 
						echo $berichtje->getText(); 
					?></a>
				</div>
				<span class="ui-icon ui-icon-arrow-r ui-icon-shadow"/>
			</div>
		</li>
	<?php } ?>
</ul>
<?php } ?>