<!DOCTYPE html>
<html>
<head>
    <title>Gouwradio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0b3/jquery.mobile-1.0b3.min.css" />
    <script src="http://code.jquery.com/jquery-1.6.2.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.0b3/jquery.mobile-1.0b3.min.js"></script>
    <link rel="stylesheet" href="/style/gouwradio.css" />
</head>
<body>
    <div data-role="page"> 
	<div data-role="header">
            <h1>Gouwradio SMS Systeem</h1>
            <div data-role="navbar">
		<ul>
                    <?php echo $this->topNavigation()->active($this->activeData); ?>
		</ul>
            </div>
        </div> 
	<div data-role="content">
            <?php echo $this->layout()->content; ?>
        </div> 
	<div data-role="footer">
            <h4>0497 21 53 60 | @gouwradio</h4>
        </div>
    </div> 
</body>
</html>