<h2>Nieuwe SMS'en</h2>
<?php if($this->noMessages) { ?>
Er zijn geen nieuwe SMS'en
<?php } else { ?>
<ul data-role="listview" data-inset="true">
	<?php foreach ($this->messages as $key => $message) { ?>
		<li>
	        <div class="nieuw-hour"><?php echo $this->DateFromEpoch()->epoch($message->getDate()); ?></div>
	        <div class="nieuw-phoneNumber"><?php echo $message->getNumber(); ?></div>
	        <div class="nieuw-text"><?php echo $message->getText(); ?></div>
	        <div data-role="controlgroup" data-type="horizontal">
	            <a href="/verzoekjes/add/id/<?php echo $message->getId();?>/" data-theme="c" data-role="button">Verzoek</a>
	            <a href="/berichtjes/add/id/<?php echo $message->getId();?>/" data-theme="c" data-role="button">Bericht</a>
	            <a href="/alles/remove/id/<?php echo $message->getId();?>/" data-theme="c" data-role="button">Verwijder</a>
	        </div>
	    </li>
    <?php } ?>
</ul>
<?php } ?>